name: ci-sphinx-build

on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      # need global jsdoc for the docs to build
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install node dependencies
        run: npm install -g jsdoc
      
      - name: Install python dependencies
        run: pip install -r docs/requirements.txt
          
      - name: Build docs
        run: sphinx-build docs/source/ docs/build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build